baseURL = "https://goodmorning-hwt.github.io/tech-blog/"
theme = "PaperMod"
defaultContentLanguage = "zh"

[params]
  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/goodmorning-hwt"

[languages]
  [languages.zh]
    languageName = "ä¸­æ–‡"
    languageCode = "zh-cn"
    title = "æˆ‘çš„æŠ€æœ¯ç¬”è®°"
    weight = 1
    [languages.zh.params]
      [languages.zh.params.homeInfoParams]
        Title = "ä½ å¥½ï¼Œæˆ‘æ˜¯ ä½•æ–‡éŸ¬ ğŸ‘‹"
        Content = "å­˜æ”¾æˆ‘çš„ç¬”è®°çš„åœ°æ–¹ã€‚"

  [languages.en]
    languageName = "English"
    languageCode = "en-us"
    title = "My Tech Notes"
    weight = 2
    [languages.en.params]
      [languages.en.params.homeInfoParams]
        Title = "Hi, I'm Wentao He ğŸ‘‹"
        Content = "A place for my notes."

# è¯·å°†ä½ çš„é…ç½®ä¿®æ”¹æˆè¿™æ ·
[markup.highlight]
  # ä¸è¦è®¾ç½® style è¿™ä¸€é¡¹ï¼ŒæŠŠå®ƒç•™ç©ºï¼Œè®©ä¸»é¢˜æ¥æ¥ç®¡é¢œè‰²
  noClasses = false # è¿™ä¸€é¡¹å¿…é¡»æ˜¯ falseï¼Œä¸»é¢˜æ‰èƒ½é€šè¿‡ CSS ç±»åæ¥åº”ç”¨æ ·å¼
  
  # å…¶ä»–é€‰é¡¹å¯ä»¥æŒ‰éœ€ä¿ç•™ï¼Œæ¯”å¦‚æ˜¾ç¤ºè¡Œå·
  lineNos = true
