baseURL = "https://goodmorning-hwt.github.io/tech-blog/"
languageCode = "zh-cn"
title = "æˆ‘çš„æŠ€æœ¯ç¬”è®°"
theme = "PaperMod"

[params]
  # ä¸»é¡µçš„æ ‡é¢˜å’Œæè¿°
  [params.homeInfoParams]
    Title = "ä½ å¥½ï¼Œæˆ‘æ˜¯ ä½•æ–‡éŸ¬ ğŸ‘‹"
    Content = "å­˜æ”¾æˆ‘çš„ç¬”è®°çš„åœ°æ–¹ã€‚"

  # ç¤¾äº¤é“¾æ¥ï¼Œå¯é€‰
  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/goodmorning-hwt"
